name: pipeline
channels:
- rdkit
- anaconda
- conda-forge
dependencies:
- rdkit==2017.09.02
- pandas==0.22.0
- luigi==2.7.5
- numpy==1.14.2
- psycopg2==2.7.4
- django==2.0.4
- djangorestframework==3.8.2
- django-extensions==2.0.7
- rdkit-postgresql==2018.03.3.0
- pip:
  - django-rest-swagger==2.2.0
